org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.12
fabric_api_version=0.161.0+26.3
modmenu_version=21.0.0
placeholder_api_version=3.2.0+26.3
junit_version=5.10.3

mod_version=1.0.3
maven_group=com.eymistaken
archives_base_name=shield-rounder
